# Generated by Django 3.2.6 on 2021-08-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zimzo_app', '0002_alter_businessmodel_business_unit_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='businessmodel',
            unique_together={('business_name', 'business_email')},
        ),
    ]
