# Generated by Django 3.2.6 on 2021-09-04 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zimzo_app', '0003_alter_businessmodel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='business_logo',
            field=models.ImageField(blank=True, null=True, upload_to='business_logo'),
        ),
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
