# Generated by Django 3.2.6 on 2021-09-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zimzo_app', '0005_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
