# Generated by Django 3.2.6 on 2021-09-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimzo_app', '0006_delete_userprofilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=8)),
            ],
            options={
                'unique_together': {('username',)},
            },
        ),
    ]
