# Generated by Django 3.2.6 on 2021-09-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zimzo_app', '0007_userprofilemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
