# Generated by Django 3.2.6 on 2021-09-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zimzo_app', '0008_alter_userprofilemodel_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
